In [1]:
import pandas as pd

In [2]:
dados = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Produto.xlsx")
dados.head(10)

   ID                  Name  Price  Id_Category
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0
5   1  Bolsa mais que Velha   8000            0
6   2                 Calça     75            0
7   3    Camisa apertadinha    170            0
8   8               Shampoo     15            1
9   9        Protetor Solar     11            1

In [3]:
#ordem crescente coluna especifica
dados   =    dados.sort_values(by=['Name'])
dados.head(7)

    ID                  Name  Price  Id_Category
18  18   A Comédia Engraçada     20            3
19  19     A História de SQL     23            3
20  20               Ai-Fone   1720            4
31  31              Almofada    170            6
48  48             Bey-Blade     55            9
43  43                  Bola    103            8
1    1  Bolsa mais que Velha   8000            0

In [11]:
#ordem crescente coluna especifica
dados=dados.sort_values(by=['Name'],ascending = True )
dados.head(7)

    ID                  Name  Price  Id_Category
18  18   A Comédia Engraçada     20            3
19  19     A História de SQL     23            3
20  20               Ai-Fone   1720            4
31  31              Almofada    170            6
48  48             Bey-Blade     55            9
43  43                  Bola    103            8
1    1  Bolsa mais que Velha   8000            0

In [8]:
#ordem crescente coluna especifica
dados=dados.sort_values(by=['Name'],ascending= False)
dados.head(7)

    ID                  Name  Price  Id_Category
35  35            Video-Game    602            7
41  41          Tornozeleira     61            8
17  17  Terror Aterrorizante     45            3
26  26               Teclado     53            5
12  12                    TV   1992            2
16  16       Suspense Demais     42            3
33  33                  Sofá    111            6

#### Renomeando Colunas

In [12]:
dados = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Produto.xlsx")
dados.head(10)

   ID                  Name  Price  Id_Category
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0
5   1  Bolsa mais que Velha   8000            0
6   2                 Calça     75            0
7   3    Camisa apertadinha    170            0
8   8               Shampoo     15            1
9   9        Protetor Solar     11            1

In [13]:
# Renomeie as colunas do DataFrame
dados = dados.rename(columns={'Name':'Nome','Price':'Preco','Id_Category':'IdCategoria'})
#[]  lista
#{}   Dicionario

In [14]:
dados.head(10)

   ID                  Nome  Preco  IdCategoria
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0
5   1  Bolsa mais que Velha   8000            0
6   2                 Calça     75            0
7   3    Camisa apertadinha    170            0
8   8               Shampoo     15            1
9   9        Protetor Solar     11            1

#### modo com variavel

In [16]:
dados = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Produto.xlsx")
dados.head(10)

   ID                  Name  Price  Id_Category
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0
5   1  Bolsa mais que Velha   8000            0
6   2                 Calça     75            0
7   3    Camisa apertadinha    170            0
8   8               Shampoo     15            1
9   9        Protetor Solar     11            1

In [17]:
# Crie um dicionário com os nomes das colunas antigos e novos
novascolunas = {'Name': 'Nome','Price': 'Valor'}
dados = dados.rename(columns = novascolunas)

In [18]:
dados.head(5)

   ID                  Nome  Valor  Id_Category
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0

Dados resumido

In [19]:
import pandas as pd  # bibliotecas

In [21]:
dados = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Produto.xlsx")
novascolunas = {'Name': 'Nome','Price': 'Valor','Id_Category':'IdCategoria'}
dados = dados.rename(columns = novascolunas)
dados.head(10)

   ID                  Nome  Valor  IdCategoria
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0
5   1  Bolsa mais que Velha   8000            0
6   2                 Calça     75            0
7   3    Camisa apertadinha    170            0
8   8               Shampoo     15            1
9   9        Protetor Solar     11            1