In [1]:
import pandas as pd

In [5]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
# extração padrão
df = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx") 
display(df)

    Vendedor  Vendas
0     Lucas      625
1      Maria     594
2    Natália     650
3   Henrique     862
4     marcos     452
5      Paula     139
6    Juliano     175
7   Gabriela     293
8      Brian     529
9      Diego     507
10     kátia     705

In [ ]:
# extração selecionando guia espesifica (sheet_name + nome da guia excel)
df = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" ,sheet_name='Planilha2' ) 
display(df)

   Titulo mesclado  Unnamed: 1
0               NaN        NaN
1               NaN        NaN
2              Loja     Vendas
3           Niterói        625
4          Curitiba        594
5    Rio de Janeiro        650
6         São Paulo        862
7            Cuiabá        452
8            Palmas        139
9          Teresina        175
10           Recife        293
11   Santa Catarina        529
12           Manaus        507
13   Belo Horizonte        705

In [17]:
# extração selecionando guia espesifica (sheet_name + nome da guia excel)
TabelaProduto = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx", sheet_name='Planilha2')
display(TabelaProduto)

   Titulo mesclado  Unnamed: 1
0               NaN        NaN
1               NaN        NaN
2              Loja     Vendas
3           Niterói        625
4          Curitiba        594
5    Rio de Janeiro        650
6         São Paulo        862
7            Cuiabá        452
8            Palmas        139
9          Teresina        175
10           Recife        293
11   Santa Catarina        529
12           Manaus        507
13   Belo Horizonte        705

In [18]:
# extração selecionando guia espesifica + pula linha (sheet_name + nome da guia excel + skiprows pula quantas linhas quiser )
#skiprows pula linha
tabelaProduto = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha2',skiprows=3)
display(tabelaProduto)

              Loja  Vendas
0          Niterói     625
1         Curitiba     594
2   Rio de Janeiro     650
3        São Paulo     862
4           Cuiabá     452
5           Palmas     139
6         Teresina     175
7           Recife     293
8   Santa Catarina     529
9           Manaus     507
10  Belo Horizonte     705

In [25]:
# escolhendo coluns espefificas (usecols  )
tabelaProduto2 = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha3')
display(tabelaProduto2)

,Vendedor,Vendas,Unnamed: 2,Unnamed: 3,Unnamed: 4,Loja,Vendas.1
0,Lucas,625,NaN,NaN,NaN,Niterói,625
1,Maria,594,NaN,NaN,NaN,Curitiba,594
2,Natália,650,NaN,NaN,NaN,Rio de Janeiro,650
3,Henrique,862,NaN,NaN,NaN,São Paulo,862
4,marcos,452,NaN,NaN,NaN,Cuiabá,452
5,Paula,139,NaN,NaN,NaN,Palmas,139
6,Juliano,175,NaN,NaN,NaN,Teresina,175
7,Gabriela,293,NaN,NaN,NaN,Recife,293
8,Brian,529,NaN,NaN,NaN,Santa Catarina,529
9,Diego,507,NaN,NaN,NaN,Manaus,507
10,kátia,705,NaN,NaN,NaN,Belo Horizonte,705

In [26]:
# escolhendo coluns espefificas (usecols)
produto = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha3',usecols='A:B')
display(produto)

    Vendedor  Vendas
0     Lucas      625
1      Maria     594
2    Natália     650
3   Henrique     862
4     marcos     452
5      Paula     139
6    Juliano     175
7   Gabriela     293
8      Brian     529
9      Diego     507
10     kátia     705

In [27]:
# escolhendo coluns espefificas (usecols  )
Loja = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha3',usecols= 'F:G')
display(Loja)

              Loja  Vendas.1
0          Niterói       625
1         Curitiba       594
2   Rio de Janeiro       650
3        São Paulo       862
4           Cuiabá       452
5           Palmas       139
6         Teresina       175
7           Recife       293
8   Santa Catarina       529
9           Manaus       507
10  Belo Horizonte       705

In [ ]:
# escolhendo coluns espefificas (usecols  )
tabelaProduto2 = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha3')
display(tabelaProduto2)

,Vendedor,Vendas,Unnamed: 2,Unnamed: 3,Unnamed: 4,Loja,Vendas.1
0,Lucas,625,NaN,NaN,NaN,Niterói,625
1,Maria,594,NaN,NaN,NaN,Curitiba,594
2,Natália,650,NaN,NaN,NaN,Rio de Janeiro,650
3,Henrique,862,NaN,NaN,NaN,São Paulo,862
4,marcos,452,NaN,NaN,NaN,Cuiabá,452
5,Paula,139,NaN,NaN,NaN,Palmas,139
6,Juliano,175,NaN,NaN,NaN,Teresina,175
7,Gabriela,293,NaN,NaN,NaN,Recife,293
8,Brian,529,NaN,NaN,NaN,Santa Catarina,529
9,Diego,507,NaN,NaN,NaN,Manaus,507
10,kátia,705,NaN,NaN,NaN,Belo Horizonte,705

In [32]:
# escolhendo coluns espefificas (usecols)  + usando uma lista 
Produto = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha3',usecols= [0,1,2])
display(Produto)

    Vendedor  Vendas  Unnamed: 2
0     Lucas      625         NaN
1      Maria     594         NaN
2    Natália     650         NaN
3   Henrique     862         NaN
4     marcos     452         NaN
5      Paula     139         NaN
6    Juliano     175         NaN
7   Gabriela     293         NaN
8      Brian     529         NaN
9      Diego     507         NaN
10     kátia     705         NaN

In [35]:
# escolhendo coluns espefificas (usecols)  + usando uma lista 
Loja = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha3',usecols= [5,6,])
display(Loja)

              Loja  Vendas.1
0          Niterói       625
1         Curitiba       594
2   Rio de Janeiro       650
3        São Paulo       862
4           Cuiabá       452
5           Palmas       139
6         Teresina       175
7           Recife       293
8   Santa Catarina       529
9           Manaus       507
10  Belo Horizonte       705

In [37]:
# escolhendo coluns espefificas    usecols + skiprows
planilha4 = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx"  , sheet_name= 'Planilha4', skiprows=7)
display(planilha4)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Vendedor,Vendas
0,NaN,NaN,NaN,NaN,NaN,NaN,Lucas,625
1,NaN,NaN,NaN,NaN,NaN,NaN,Maria,594
2,NaN,NaN,NaN,NaN,NaN,NaN,Natália,650
3,NaN,NaN,NaN,NaN,NaN,NaN,Henrique,862
4,NaN,NaN,NaN,NaN,NaN,NaN,marcos,452
5,NaN,NaN,NaN,NaN,NaN,NaN,Paula,139
6,NaN,NaN,NaN,NaN,NaN,NaN,Juliano,175
7,NaN,NaN,NaN,NaN,NaN,NaN,Gabriela,293
8,NaN,NaN,NaN,NaN,NaN,NaN,Brian,529
9,NaN,NaN,NaN,NaN,NaN,NaN,Diego,507
10,NaN,NaN,NaN,NaN,NaN,NaN,kátia,705

In [42]:
# escolhendo coluns espefificas    usecols + skiprows
planilha4 = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx"  , sheet_name= 'Planilha4',usecols='G:H',skiprows=7)
display(planilha4)

    Vendedor  Vendas
0     Lucas      625
1      Maria     594
2    Natália     650
3   Henrique     862
4     marcos     452
5      Paula     139
6    Juliano     175
7   Gabriela     293
8      Brian     529
9      Diego     507
10     kátia     705

In [8]:
#skiprows = pula linha 
#nrows = seleciona até a quantidade de linhas que voce quiser
Planilha4 = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha5', usecols= 'A:B',skiprows=3,nrows=20)
display(Planilha4)

           Natália     650
0         Henrique     862
1           marcos     452
2            Paula     139
3          Juliano     175
4         Gabriela     293
5            Brian     529
6            Diego     507
7            kátia     705
8              NaN     NaN
9             Loja  Vendas
10         Niterói     625
11        Curitiba     594
12  Rio de Janeiro     650
13       São Paulo     862
14          Cuiabá     452
15          Palmas     139
16        Teresina     175
17          Recife     293
18  Santa Catarina     529
19          Manaus     507

In [9]:
#skiprows = pula linha 
#nrows = seleciona até a quantidade de linhas que voce quiser 
produto = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha5' , nrows= 11)
display(produto)

    Vendedor  Vendas
0     Lucas      625
1      Maria     594
2    Natália     650
3   Henrique     862
4     marcos     452
5      Paula     139
6    Juliano     175
7   Gabriela     293
8      Brian     529
9      Diego     507
10     kátia     705

In [ ]:
#skiprows = pula linha 
#nrows = seleciona até a quantidade de linhas que voce quiser 
Loja = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha5' , skiprows= 13)
display(Loja)

   Santa Catarina  529
0          Manaus  507
1  Belo Horizonte  705

In [3]:
Loja = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha5' ,usecols='G:H', skiprows=13)
display(Loja)

     a   b
0  NaN NaN
1  NaN NaN
2  NaN NaN
3  NaN NaN
4  NaN NaN
5  NaN NaN
6  NaN NaN
7  NaN NaN
8  NaN NaN
9  NaN NaN
10 NaN NaN

In [5]:
Loja =pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Caquinha.xlsx" , sheet_name= 'Planilha5' , nrows=11)
display(Loja)

    Vendedor  Vendas
0     Lucas      625
1      Maria     594
2    Natália     650
3   Henrique     862
4     marcos     452
5      Paula     139
6    Juliano     175
7   Gabriela     293
8      Brian     529
9      Diego     507
10     kátia     705